### ISSUE TITLE
About documentation

### ISSUE THREAD

**Issue by LovelyBuggies** [PicGo/PicGo-Doc#4]
Hey, PicGo experts!

I have been a user of your APP for a long time. Although PicGo is easy to grasp, I think it would be nice to add documentation pages or website on your organization or at least this repo to introduce PicGo. I recommend you to use Sphinx and host on Read the Docs (numpy style) rather than just make some simple Markdown files in this repo. If you need help, I am willing to participate yours! Thanks.

**Comment by Molunerfinn** [comment]
Thanks but you can visit this documentation with this [link](https://picgo.github.io/PicGo-Doc/), it's built by vuepress!

BTW, if you can help me to translate the Chinese version to the English version, it would be very helpful!

Thanks for supporting this project~

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/78370586-6a5ce200-75f9-11ea-91d0-39dd00aaaa05.png)

**Comment by LovelyBuggies** [comment]
> BTW, if you can help me to translate the Chinese version to the English version, it would be very helpful!
> 
> 
> 
> Thanks for supporting this project~

Actually, I could and my time is available. Tell me where to start and how can I help/join U :)

**Comment by Molunerfinn** [comment]
> > BTW, if you can help me to translate the Chinese version to the English version, it would be very helpful!
> > Thanks for supporting this project~
> 
> Actually, I could and my time is available. Tell me where to start and how can I help/join U :)

Thanks! I have already sent an email to you!
